### PR TITLE
Let statuser track hangs by counting EVENTLOOP_UI_ACTIVITY_EXP_MS > 50ms samples

### PR DESCRIPTION
**Pull request by mikeconley**

### CODE REVIEW

**Comment by chutten** [comment]
Don't we also need a new, built, signed version of this to go with the PR? (not sure)

**Comment by mikeconley** [comment]
Yep. I could build one and sign with my own key if you'd like and add it to the dist directory. Depends on if you want to be the one on the hook if it gets revoked. ;)

Let me know if you'd rather I just do it.

**Comment by chutten** [comment]
I think I can trust you to do it :) 

Signing this is a formality we need to observe, not something crucial to the users who'll be using this addon.

**Comment by mikeconley** [comment]
Bah, it's not letting me sign it because I don't own it. :/

```
JPM [warning] Using existing install.rdf. This file is usually auto-generated.
Creating XPI
JPM [info] XPI created at C:\Users\mconley\AppData\Local\Temp\tmp-unsigned-xpi-3540gdIq8sNGW575\@statuser-0.0.4.xpi (98ms)
Created XPI at C:\Users\mconley\AppData\Local\Temp\tmp-unsigned-xpi-3540gdIq8sNGW575\@statuser-0.0.4.xpi
JPM [info] Created XPI for signing: C:\Users\mconley\AppData\Local\Temp\tmp-unsigned-xpi-3540gdIq8sNGW575\@statuser-0.0.4.xpi
JPM [error] Server response: You do not own this addon. ( status: 403 )
JPM [info] FAIL
```

**Comment by chutten** [comment]
*sad trombone*

Alrighty, I guess this'll be my contribution to the fun. I'll merge, rebase, build, push... yeesh.

**Pull request merged**
