### PR TITLE
Spin the icon on loading (fixes #12)

### LINKED ISSUE #12: statuser no longer spins during pageload.
Nightly 46. Page loads are supposed to spin the statuser icon in a lopsided manner (see [`onStateChange`](https://github.com/chutten/statuser/blob/gh-pages/index.js#L123)), but they don't.

### PR DESCRIPTION
**Pull request by Uberi**
Fix the interface for nsIWebProgressListener, so the icon spins around when any page is in the loading state.

It looks like this:

screenshot from 2016-01-18 18-24-03

Note that this will not work until the browser is restarted after installation, since it is not part of the restartless addon functionality.

### CODE REVIEW

**Comment by chutten** [comment]
You changed so much in this patch, it's hard to determine what the fix actually was. Can you break this into two patches: one that does whatever cleanup you feel is necessary, and a second that actually fixes the bug?

**Comment by Uberi** [comment]
I rebased the commit, after removing the cleanup lines; it just contains the fix now. Basically, we're now using explicit object literals to define XPCOM interfaces instead of `exports`.

**Comment by chutten** [comment]
What was the "fix" then, that got it to spin properly?

**Comment by Uberi** [comment]
Rebased off gh-pages.

It doesn't seem to like there being non-interface methods in the interface object (like `observe` being in the definition for `nsIWebProgressListener`). I could investigate why exactly, but for now this works quite well.

**Pull request merged**
